# -*- coding: utf-8 -*-
"""Corpus.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18yuPDYcp4lI9bLO18JKM1tRNT6zh7bMv

#Corpus

Sua  tarefa  será  transformar  um  conjunto  de  5  sites,  sobre  o  tema  de  processamento  de 
linguagem natural em um conjunto de cinco listas distintas de sentenças. Ou seja, você fará uma função 
que, usando a biblioteca Beautifull Soap, faça a requisição de uma url, e extrai todas as sentenças desta 
url. Duas condições são importantes:  
>  a) A página web (url) deve apontar para uma página web em inglês contendo, não menos que 1000 palavras.  

> b) O texto desta página deverá ser transformado em um array de senteças.  
 
Para separar as sentenças você pode usar os sinais de pontuação ou as funções da biblibioteca 
Spacy.
"""

import requests
import spacy
import bs4
from bs4 import BeautifulSoup

def adiciona_site(site, lista):

  page = requests.get(site)
  if  not 200==page.status_code:
    print("Site: "+site+" não abriu")
    print(page.status_code)
    return lista
  soap = BeautifulSoup(page.content, 'html.parser')

  spaci = spacy.load('en_core_web_sm')

  
  for i in soap.find_all('p'):
    espaco = spaci(i.get_text())
    for j in espaco.sents:
      lista.append(j)
  return lista

sentencas = []
sentencas1 = adiciona_site("https://www.techtarget.com/searchenterpriseai/definition/natural-language-processing-NLP", [])
sentencas2 = adiciona_site("https://www.sas.com/en_us/insights/analytics/what-is-natural-language-processing-nlp.html#world", [])
sentencas3 = adiciona_site("https://monkeylearn.com/natural-language-processing/", [])
sentencas4 = adiciona_site("https://hbr.org/2022/04/the-power-of-natural-language-processing", [])
sentencas5 = adiciona_site("https://www.oracle.com/artificial-intelligence/what-is-natural-language-processing/", [])
sentencas.append(sentencas1)
sentencas.append(sentencas2)
sentencas.append(sentencas3)
sentencas.append(sentencas4)
sentencas.append(sentencas5)
print(sentencas)